#select 'id' AS `id`,'title' AS `title`,'price' AS `price`,'Image_link' AS `Image_link`,'link' AS `link`,'description' AS `description`,'condition' AS `condition`,'mpn' AS `mpn`,'brand' AS `brand`,'product_type' AS `product_type`,'google_product_category' AS `google_product_category`,'availability' AS `availability`,'shipping_weight' AS `shipping_weight`,'adwords_labels' AS `adwords_labels`,'color' AS `color`,'material' AS `material`,'shipping' AS `shipping`,'item group id' AS `item group id` union 
set @storeid=0;
SELECT `e`.entity_id AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `title`, CONCAT(truncate(`at_price`.`value`,2),'USD') AS `price`, CONCAT('http://www.xxx.com/media/catalog/product',min(at_image.`value`)) AS `Image_link`, CONCAT('http://www.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, `at_meta_description`.`value` AS `description`, 'New' as `condition`,CONCAT('ENMLED',`e`.sku) AS `mpn`, 'xxx' AS `brand`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) ))  AS `product_type`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google_product_category`, 'in stock' AS availability, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `shipping_weight`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords_labels`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=1) AS `color`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=1) AS `material`, ':::' AS `shipping`, `e`.entity_id AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '72') AND (`at_description`.`store_id` = 0) 
WHERE `at_status`.`value` = 1 
GROUP BY e.entity_id

set @storeid=6;
SELECT CONCAT(`e`.entity_id,'-de') AS `ID`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `Titel`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='EUR'),2),'EUR') AS `Preis`, CONCAT('http://de.xxx.com/media/catalog/product',min(at_image.`value`)) AS `Bildlink`, CONCAT('http://de.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `Link`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `Beschreibung`, 'Neu' as `Zustand`, CONCAT('ENMLED',`e`.sku) AS `MPN`, 'xxx' AS `Marke`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ))  AS `Produkttyp`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google_product_category`, 'Auf Lager' AS Verfügbarkeit, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `versandgewicht`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `Adwords labels`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=@storeid) AS `Farbe`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=@storeid) AS `material`, ':::' AS `Versand`, CONCAT(`e`.entity_id,'-de') AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
WHERE `at_status`.`value` = 1 and (`at_name`.`value_id` > 0)
GROUP BY e.entity_id


set @storeid=7;
SELECT CONCAT(`e`.entity_id,'-fr') AS `identifiant`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `titre`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='EUR'),2),'EUR') AS `prix`, CONCAT('http://fr.xxx.com/media/catalog/product',min(at_image.`value`)) AS `lien image`, CONCAT('http://fr.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `lien`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `description`, 'neuf' as `état`, CONCAT('ENMLED',`e`.sku) AS `référence fabricant`, 'xxx' AS `marque`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ))  AS `catégorie`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `catégorie de produits Google`, 'en stock' AS disponibilité, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `poids du colis`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords étiquettes`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=@storeid) AS `couleur`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=@storeid) AS `matière`, ':::' AS `Livraison`, CONCAT(`e`.entity_id,'-fr') AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
WHERE `at_status`.`value` = 1 and (`at_name`.`value_id` > 0)
GROUP BY e.entity_id


set @storeid=8;
SELECT CONCAT(`e`.entity_id,'-es') AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `título`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='EUR'),2),'EUR') AS `precio`, CONCAT('http://es.xxx.com/media/catalog/product',min(at_image.`value`)) AS `enlace_imagen`, CONCAT('http://es.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `enlace`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `descripción`, 'nuevo' as `estado`, CONCAT('ENMLED',`e`.sku) AS `MPN`, 'xxx' AS `marca`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ))  AS `categoría`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `categoría en google product`, 'en stock' AS disponibilidad, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `peso de embarque`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords etiquetas`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=@storeid) AS `color`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=@storeid) AS `material`, ':::' AS `envío`, `e`.entity_id AS `identificador de grupo`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
WHERE `at_status`.`value` = 1 and (`at_name`.`value_id` > 0)
GROUP BY e.entity_id


set @storeid=9;
SELECT CONCAT(`e`.entity_id,'-it') AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `titolo`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='EUR'),2),'EUR') AS `prezzo`, CONCAT('http://it.xxx.com/media/catalog/product',min(at_image.`value`)) AS `link_immagine`, CONCAT('http://it.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `descrizione`, 'nuovo' as `condizione`, CONCAT('ENMLED',`e`.sku) AS `MPN`, 'xxx' AS `marca`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ))  AS `tipo di prodotto`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `categoria prodotto google`, 'disponibile' AS disponibilità, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `peso spedizione`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords etichette`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=@storeid) AS `colore`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=@storeid) AS `materiale`, ':::' AS `spedizione`, CONCAT(`e`.entity_id,'-it') AS `identificatore di gruppo`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
WHERE `at_status`.`value` = 1 and (`at_name`.`value_id` > 0)
GROUP BY e.entity_id


set @storeid=11;
SELECT CONCAT(`e`.entity_id,'-jp') AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `商品名`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='JPY'),2),'JPY') AS `価格`, CONCAT('http://www.xxx.com/media/catalog/product',min(at_image.`value`)) AS `商品画像リンク`, CONCAT('http://www.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `商品リンク`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `商品説明`, '新品' as `状態`, CONCAT('ENMLED',`e`.sku) AS `MPN`, 'xxx' AS `ブランド`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ))  AS `商品カテゴリ`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google 商品カテゴリ`, '在庫あり' AS `在庫状況`, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `搬送重量`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `アドワーズ用ラベル`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=@storeid) AS `色`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=@storeid) AS `素材`, ':::' AS `送料`, CONCAT(`e`.entity_id,'-jp') AS `アイテム グループ id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '72') AND (`at_description`.`store_id` = 0) 
WHERE `at_status`.`value` = 1 and (`at_name`.`value_id` > 0)
GROUP BY e.entity_id


set @storeid=10;
SELECT CONCAT(`e`.entity_id,'-pt') AS `código`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `título`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='EUR'),2),'EUR') AS `pre?o`, CONCAT('http://pt.xxx.com/media/catalog/product',min(at_image.`value`)) AS `link da imagem`, CONCAT('http://pt.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `descri??o`, 'novo' as `estado`, CONCAT('ENMLED',`e`.sku) AS `MPN`, 'xxx' AS `marca`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ))  AS `tipo de produto`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `categoria google do produto`, 'em estoque' AS 'disponibilidade', CONCAT(truncate(`at_weight`.`value`,0),'g') AS `peso com embalagem`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords etiquetas`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=@storeid) AS `cor`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=@storeid) AS `material`, ':::' AS `frete`, CONCAT(`e`.entity_id,'-pt') AS `código de grupo`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
WHERE `at_status`.`value` = 1 and (`at_name`.`value_id` > 0)
GROUP BY e.entity_id



##########################################################
set @storeid=0;
SELECT `e`.entity_id AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `title`, CONCAT(truncate(`at_price`.`value`,2),'USD') AS `price`, CONCAT('http://www.xxx.com/media/catalog/product',min(at_image.`value`)) AS `Image_link`, CONCAT('http://www.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, concat(IF(at_meta_description.`value` <> '', `at_meta_description`.`value`, at_name_default.`value`),'. ',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(at_description.`value`,' align="center"','. '),'</p>','. '),'<br>','. '),'<br/>','. '),'<br />','. '),'<p>',' '),'<li>',' '),'&nbsp;',' '),'&plusmn;',' '),'&oslash;',' '),'<tr>',' '),'</tr>',' '),'</td>',' '),'<td>',' '),'</li>',' '),'</ul>',' '),'<ul>',' '),'</div>',' '),'<div>',' '), CHAR(10), '. '), CHAR(13), '. '), CHAR(9), ' ')) AS `description`, 'New' as `condition`,CONCAT('ENMLED',`e`.sku) AS `mpn`, 'xxx' AS `brand`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) ))  AS `product_type`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google_product_category`, 'in stock' AS availability, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `shipping_weight`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords_labels`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=1) AS `color`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=1) AS `material`, ':::' AS `shipping`, `e`.entity_id AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '72') AND (`at_description`.`store_id` = 0) 
WHERE `at_status`.`value` = 1
GROUP BY e.entity_id
#LIMIT 1


set @storeid=0;
SELECT CONCAT(`e`.entity_id,'-ca') AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `title`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='CAD'),2),'CAD') AS `price`, CONCAT('http://www.xxx.com/media/catalog/product',min(at_image.`value`)) AS `Image_link`, CONCAT('http://www.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, concat(IF(at_meta_description.`value` <> '', `at_meta_description`.`value`, at_name_default.`value`),'. ',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(at_description.`value`,' align="center"','. '),'</p>','. '),'<br>','. '),'<br/>','. '),'<br />','. '),'<p>',' '),'<li>',' '),'&nbsp;',' '),'&plusmn;',' '),'&oslash;',' '),'<tr>',' '),'</tr>',' '),'</td>',' '),'<td>',' '),'</li>',' '),'</ul>',' '),'<ul>',' '),'</div>',' '),'<div>',' '), CHAR(10), '. '), CHAR(13), '. '), CHAR(9), ' ')) AS `description`, 'New' as `condition`,CONCAT('ENMLED',`e`.sku) AS `mpn`, 'xxx' AS `brand`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) ))  AS `product_type`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google_product_category`, 'in stock' AS availability, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `shipping_weight`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords_labels`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=1) AS `color`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=1) AS `material`, ':::' AS `shipping`, CONCAT(`e`.entity_id,'-ca') AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '72') AND (`at_description`.`store_id` = 0) 
WHERE `at_status`.`value` = 1
GROUP BY e.entity_id
#LIMIT 1


set @storeid=0;
SELECT CONCAT(`e`.entity_id,'-au') AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `title`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='AUD'),2),'AUD') AS `price`, CONCAT('http://www.xxx.com/media/catalog/product',min(at_image.`value`)) AS `Image_link`, CONCAT('http://www.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, concat(IF(at_meta_description.`value` <> '', `at_meta_description`.`value`, at_name_default.`value`),'. ',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(at_description.`value`,' align="center"','. '),'</p>','. '),'<br>','. '),'<br/>','. '),'<br />','. '),'<p>',' '),'<li>',' '),'&nbsp;',' '),'&plusmn;',' '),'&oslash;',' '),'<tr>',' '),'</tr>',' '),'</td>',' '),'<td>',' '),'</li>',' '),'</ul>',' '),'<ul>',' '),'</div>',' '),'<div>',' '), CHAR(10), '. '), CHAR(13), '. '), CHAR(9), ' ')) AS `description`, 'New' as `condition`,CONCAT('ENMLED',`e`.sku) AS `mpn`, 'xxx' AS `brand`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) ))  AS `product_type`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google_product_category`, 'in stock' AS availability, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `shipping_weight`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords_labels`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=1) AS `color`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=1) AS `material`, ':::' AS `shipping`, CONCAT(`e`.entity_id,'-au') AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '72') AND (`at_description`.`store_id` = 0) 
WHERE `at_status`.`value` = 1
GROUP BY e.entity_id
#LIMIT 1


set @storeid=0;
SELECT CONCAT(`e`.entity_id,'-uk') AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `title`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='GBP'),2),'GBP') AS `price`, CONCAT('http://www.xxx.com/media/catalog/product',min(at_image.`value`)) AS `Image_link`, CONCAT('http://www.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, concat(IF(at_meta_description.`value` <> '', `at_meta_description`.`value`, at_name_default.`value`),'. ',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(at_description.`value`,' align="center"','. '),'</p>','. '),'<br>','. '),'<br/>','. '),'<br />','. '),'<p>',' '),'<li>',' '),'&nbsp;',' '),'&plusmn;',' '),'&oslash;',' '),'<tr>',' '),'</tr>',' '),'</td>',' '),'<td>',' '),'</li>',' '),'</ul>',' '),'<ul>',' '),'</div>',' '),'<div>',' '), CHAR(10), '. '), CHAR(13), '. '), CHAR(9), ' ')) AS `description`, 'New' as `condition`,CONCAT('ENMLED',`e`.sku) AS `mpn`, 'xxx' AS `brand`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) ))  AS `product_type`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google_product_category`, 'in stock' AS availability, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `shipping_weight`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords_labels`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=1) AS `color`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=1) AS `material`, ':::' AS `shipping`, CONCAT(`e`.entity_id,'-uk') AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '72') AND (`at_description`.`store_id` = 0) 
WHERE `at_status`.`value` = 1
GROUP BY e.entity_id
#LIMIT 1


set @storeid=0;
SELECT CONCAT(`e`.entity_id,'-nl') AS `id`, IF(at_name.value_id > 0, at_name.value, at_name_default.value) AS `title`, CONCAT(truncate(`at_price`.`value`*(SELECT rate FROM `directory_currency_rate` where currency_from = 'USD' and currency_to='EUR'),2),'EUR') AS `price`, CONCAT('http://www.xxx.com/media/catalog/product',min(at_image.`value`)) AS `Image_link`, CONCAT('http://www.xxx.com/p',`e`.entity_id,'-',`at_url_key`.`value`,'.html') AS `link`, concat(IF(at_meta_description.`value` <> '', `at_meta_description`.`value`, at_name_default.`value`),'. ',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(at_description.`value`,' align="center"','. '),'</p>','. '),'<br>','. '),'<br/>','. '),'<br />','. '),'<p>',' '),'<li>',' '),'&nbsp;',' '),'&plusmn;',' '),'&oslash;',' '),'<tr>',' '),'</tr>',' '),'</td>',' '),'<td>',' '),'</li>',' '),'</ul>',' '),'<ul>',' '),'</div>',' '),'<div>',' '), CHAR(10), '. '), CHAR(13), '. '), CHAR(9), ' ')) AS `description`, 'New' as `condition`,CONCAT('ENMLED',`e`.sku) AS `mpn`, 'xxx' AS `brand`, CONCAT((SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid)),' > ', (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) ))  AS `product_type`, 'Home & Garden > Lighting > Light Bulbs > LED Light Bulbs' AS `google_product_category`, 'in stock' AS availability, CONCAT(truncate(`at_weight`.`value`,0),'g') AS `shipping_weight`, (SELECT `at_category_name`.`value` FROM `catalog_category_entity_varchar` AS `at_category_name` WHERE (`at_category_name`.`entity_id` = max(`at_category`.`entity_id`)) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = 0) ) AS `adwords_labels`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_light_color`.`value`,',',1) and eaov.store_id=1) AS `color`, (SELECT eaov.`value` FROM `eav_attribute_option_value` as eaov where eaov.option_id=substring_index(`at_material`.`value`,',',1) and eaov.store_id=1) AS `material`, ':::' AS `shipping`, CONCAT(`e`.entity_id,'-nl') AS `item group id`
FROM `catalog_product_entity` AS `e` 
INNER JOIN `catalog_product_entity_varchar` AS `at_name_default` ON (`at_name_default`.`entity_id` = `e`.`entity_id`) AND (`at_name_default`.`attribute_id` = '71') AND `at_name_default`.`store_id` = 0 
LEFT JOIN `catalog_product_entity_varchar` AS `at_name` ON (`at_name`.`entity_id` = `e`.`entity_id`) AND (`at_name`.`attribute_id` = '71') AND (`at_name`.`store_id` = @storeid) 
INNER JOIN `catalog_product_entity_decimal` AS `at_price` ON (`at_price`.`entity_id` = `e`.`entity_id`) AND (`at_price`.`attribute_id` = '75') AND (`at_price`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_varchar` AS `at_url_key` ON (`at_url_key`.`entity_id` = `e`.`entity_id`) AND (`at_url_key`.`attribute_id` = '97') AND (`at_url_key`.`store_id` = 0) 
INNER JOIN `catalog_product_entity_decimal` AS `at_weight` ON (`at_weight`.`entity_id` = `e`.`entity_id`) AND (`at_weight`.`attribute_id` = '80') AND (`at_weight`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_media_gallery` AS `at_image` ON (`at_image`.`entity_id` = `e`.`entity_id`) AND (`at_image`.`attribute_id` = '88')
LEFT JOIN `catalog_category_product` AS `at_category_product` ON (`at_category_product`.product_id = `e`.`entity_id`)
LEFT JOIN `catalog_category_entity` AS `at_category` ON (`at_category_product`.category_id = `at_category`.`entity_id`) #AND (`at_category`.parent_id<>3) 
LEFT JOIN `catalog_category_entity_varchar` AS `at_category_name` ON (`at_category_name`.`entity_id` = `at_category`.`entity_id`) AND (`at_category_name`.`attribute_id` = '41') AND (`at_category_name`.`store_id` = @storeid) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_meta_description` ON (`at_meta_description`.`entity_id` = `e`.`entity_id`) AND (`at_meta_description`.`attribute_id` = '84') AND (`at_meta_description`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_int` AS `at_status` ON (`at_status`.`entity_id` = `e`.`entity_id`) AND (`at_status`.`attribute_id` = '96') AND (`at_status`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_light_color` ON (`at_light_color`.`entity_id` = `e`.`entity_id`) AND (`at_light_color`.`attribute_id` = '161') AND (`at_light_color`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_varchar` AS `at_material` ON (`at_material`.`entity_id` = `e`.`entity_id`) AND (`at_material`.`attribute_id` = '165') AND (`at_material`.`store_id` = 0) 
LEFT JOIN `catalog_product_entity_text` AS `at_description` ON (`at_description`.`entity_id` = `e`.`entity_id`) AND (`at_description`.`attribute_id` = '72') AND (`at_description`.`store_id` = 0) 
WHERE `at_status`.`value` = 1
GROUP BY e.entity_id
#LIMIT 1